services:
  - type: web
    name: churchiligan
    runtime: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn ChurchIligan.wsgi:application -c gunicorn.conf.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "churchiligan.onrender.com,127.0.0.1,localhost"
      - key: DATABASE_URL
        fromDatabase:
          name: churchiligan-db
          property: connectionString
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://churchiligan.onrender.com,http://127.0.0.1:8000,http://localhost:8000"
      - key: GOOGLE_OAUTH_CLIENT_ID
        value: ""
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        value: ""
      - key: GOOGLE_OAUTH_REDIRECT_URI
        value: "https://churchiligan.onrender.com/google/callback/"
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"
      - key: EMAIL_HOST
        value: "smtp-relay.brevo.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        value: "979d0a001@smtp-brevo.com"
      - key: EMAIL_HOST_PASSWORD
        value: "OrM1ztRFCjEm2bks"
      - key: EMAIL_TIMEOUT
        value: "10"
      - key: DEFAULT_FROM_EMAIL
        value: "ChurchConnect <marllouie4@gmail.com>"
      - key: GOOGLE_OAUTH_CLIENT_ID
        value: "1053022434620-53ddgsjm3docsougushcna2a5hoqe0vd.apps.googleusercontent.com"
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        value: "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"
      - key: GOOGLE_OAUTH_REDIRECT_URI
        value: "https://churchiligan.onrender.com/google/callback/"
      - key: STATIC_VERSION
        value: "1"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "marllouie4@gmail.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "admin123secure"

databases:
  - name: churchiligan-db
    plan: free
    databaseName: churchiligan
    user: churchiligan
