# Generated by Django 5.2.6 on 2025-09-19 17:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Church name', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', unique=True)),
                ('description', models.TextField(help_text='Brief description of the church')),
                ('denomination', models.CharField(choices=[('catholic', 'Catholic'), ('protestant', 'Protestant'), ('baptist', 'Baptist'), ('methodist', 'Methodist'), ('presbyterian', 'Presbyterian'), ('lutheran', 'Lutheran'), ('pentecostal', 'Pentecostal'), ('evangelical', 'Evangelical'), ('orthodox', 'Orthodox'), ('adventist', 'Seventh-day Adventist'), ('mormon', 'Latter-day Saints'), ('jehovah', "Jehovah's Witnesses"), ('other', 'Other')], default='other', max_length=20)),
                ('size', models.CharField(choices=[('small', 'Small (1-50 members)'), ('medium', 'Medium (51-200 members)'), ('large', 'Large (201-1000 members)'), ('mega', 'Mega (1000+ members)')], default='medium', max_length=10)),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('phone', models.CharField(help_text='Primary contact phone number', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('website', models.URLField(blank=True, help_text='Church website URL', null=True)),
                ('address', models.TextField(help_text='Street address')),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State/Province', max_length=100)),
                ('country', models.CharField(default='Philippines', help_text='Country', max_length=100)),
                ('postal_code', models.CharField(help_text='Postal/ZIP code', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for mapping', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for mapping', max_digits=9, null=True)),
                ('pastor_name', models.CharField(help_text='Lead pastor/minister name', max_length=100)),
                ('pastor_email', models.EmailField(blank=True, help_text="Pastor's email", max_length=254, null=True)),
                ('pastor_phone', models.CharField(blank=True, help_text="Pastor's phone number", max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('logo', models.ImageField(blank=True, help_text='Church logo', null=True, upload_to='churches/logos/')),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image for church profile', null=True, upload_to='churches/covers/')),
                ('service_times', models.TextField(help_text='Service times and schedule (e.g., Sunday 9:00 AM, 11:00 AM)')),
                ('special_services', models.TextField(blank=True, help_text='Special services or events')),
                ('ministries', models.TextField(blank=True, help_text='Available ministries and programs')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL', null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this church is verified by administrators')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this church is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_count', models.PositiveIntegerField(default=0, help_text='Approximate number of members')),
                ('follower_count', models.PositiveIntegerField(default=0, help_text='Number of users following this church')),
                ('owner', models.ForeignKey(help_text='User who created/manages this church', on_delete=django.db.models.deletion.CASCADE, related_name='owned_churches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Church',
                'verbose_name_plural': 'Churches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChurchFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='core.church')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-followed_at'],
                'unique_together': {('user', 'church')},
            },
        ),
    ]
