# Generated by Django 5.2.6 on 2025-09-19 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookableService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name (e.g., Counseling Session, Baptism)', max_length=200)),
                ('description', models.TextField(help_text='Description of the service')),
                ('duration', models.PositiveIntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '1 hour'), (90, '1.5 hours'), (120, '2 hours'), (180, '3 hours')], default=60, help_text='Service duration in minutes')),
                ('max_bookings_per_day', models.PositiveIntegerField(default=10, help_text='Maximum number of bookings per day')),
                ('advance_booking_days', models.PositiveIntegerField(default=30, help_text='How many days in advance can this be booked')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is available for booking')),
                ('requires_approval', models.BooleanField(default=False, help_text='Whether bookings require church approval')),
                ('preparation_notes', models.TextField(blank=True, help_text='Notes for people booking this service')),
                ('cancellation_policy', models.TextField(blank=True, help_text='Cancellation policy for this service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookable_services', to='core.church')),
            ],
            options={
                'verbose_name': 'Bookable Service',
                'verbose_name_plural': 'Bookable Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for this availability entry')),
                ('type', models.CharField(choices=[('closed_date', 'Closed Date'), ('reduced_hours', 'Reduced Hours'), ('special_hours', 'Special Hours')], default='closed_date', max_length=20)),
                ('is_closed', models.BooleanField(default=True, help_text='Whether the church is closed on this date')),
                ('start_time', models.TimeField(blank=True, help_text='Start time for special hours', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time for special hours', null=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for closure or special hours', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='core.church')),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availability',
                'ordering': ['-date'],
                'unique_together': {('church', 'date')},
            },
        ),
    ]
