# Generated by Django 5.2.6 on 2025-09-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bookableservice_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookableservice',
            name='image',
            field=models.ImageField(blank=True, help_text='Service image', null=True, upload_to='services/images/'),
        ),
        migrations.AddField(
            model_name='bookableservice',
            name='is_free',
            field=models.BooleanField(default=True, help_text='Whether this service is free'),
        ),
        migrations.AddField(
            model_name='bookableservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Service price (optional)', max_digits=10, null=True),
        ),
    ]
