# Generated by Django 5.2.6 on 2025-09-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bookableservice_image_bookableservice_is_free_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookableservice',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the service (optional)'),
        ),
    ]
