# Generated by Django 5.2.6 on 2025-09-20 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_make_service_description_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookableservice',
            name='currency',
            field=models.CharField(default='PHP', help_text='Currency code (e.g., PHP, USD)', max_length=3),
        ),
        migrations.AlterField(
            model_name='bookableservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Service price', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Service image', upload_to='services/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Image caption (optional)', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image for service card')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_images', to='core.bookableservice')),
            ],
            options={
                'verbose_name': 'Service Image',
                'verbose_name_plural': 'Service Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
