# Generated by Django 5.2.6 on 2025-09-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_service_pricing_and_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookableservice',
            name='currency',
            field=models.CharField(choices=[('PHP', 'Philippine Peso (₱)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('KRW', 'South Korean Won (₩)'), ('SGD', 'Singapore Dollar (S$)'), ('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (C$)')], default='PHP', help_text='Currency for pricing', max_length=3),
        ),
    ]
