# Generated by Django 5.2.6 on 2025-09-20 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_currency_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Human-readable appointment ID e.g., APPT-0001', max_length=20, unique=True)),
                ('date', models.DateField(help_text='Requested date')),
                ('start_time', models.TimeField(blank=True, help_text='Optional start time (slots to be implemented)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Optional end time', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes provided by requester')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('completed', 'Completed'), ('declined', 'Declined'), ('canceled', 'Canceled')], default='requested', max_length=20)),
                ('cancel_reason', models.CharField(blank=True, help_text='Reason when canceled/auto-canceled', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.church')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.bookableservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service', 'date', 'status'], name='core_bookin_service_238919_idx'), models.Index(fields=['church', 'status'], name='core_bookin_church__467b8a_idx'), models.Index(fields=['user', 'status'], name='core_bookin_user_id_a894ef_idx')],
            },
        ),
    ]
