# Generated by Django 5.2.6 on 2025-09-21 02:57

from django.db import migrations, models
from django.utils.text import slugify


def update_church_slugs(apps, schema_editor):
    """Update empty or missing slugs for existing churches."""
    Church = apps.get_model('core', 'Church')
    
    # Get churches with empty or null slugs
    churches_without_slugs = Church.objects.filter(
        models.Q(slug__isnull=True) | models.Q(slug='')
    )
    
    for church in churches_without_slugs:
        if church.name:
            # Generate slug from name
            base_slug = slugify(church.name)
            slug = base_slug
            counter = 1
            
            # Ensure uniqueness
            while Church.objects.filter(slug=slug).exclude(pk=church.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            church.slug = slug
            church.save(update_fields=['slug'])


def reverse_update_church_slugs(apps, schema_editor):
    """Reverse migration - set slugs back to empty."""
    Church = apps.get_model('core', 'Church')
    Church.objects.all().update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification'),
    ]

    operations = [
        migrations.RunPython(update_church_slugs, reverse_update_church_slugs),
    ]
