# Generated by Django 5.2.6 on 2025-09-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_update_church_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='decline_reason',
            field=models.CharField(blank=True, help_text='Reason when declined', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_requested', 'New Booking Request'), ('booking_reviewed', 'Booking Reviewed'), ('booking_approved', 'Booking Approved'), ('booking_declined', 'Booking Declined'), ('booking_canceled', 'Booking Canceled'), ('booking_completed', 'Booking Completed'), ('church_approved', 'Church Approved'), ('church_declined', 'Church Declined'), ('follow_request', 'Follow Request'), ('follow_accepted', 'Follow Accepted')], max_length=50),
        ),
        migrations.CreateModel(
            name='DeclineReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Reason label shown when declining a booking', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sorting order (0 first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decline_reasons', to='core.church')),
            ],
            options={
                'verbose_name': 'Decline Reason',
                'verbose_name_plural': 'Decline Reasons',
                'ordering': ['order', 'id'],
                'unique_together': {('church', 'label')},
            },
        ),
    ]
