# Generated by Django 5.2.6 on 2025-09-22 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_postcomment_postlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this post has been viewed'),
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the viewer')),
                ('user_agent', models.TextField(help_text='User agent string', max_length=500)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to='core.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['post', 'viewed_at'], name='core_postvi_post_id_7c36c8_idx'), models.Index(fields=['user', 'viewed_at'], name='core_postvi_user_id_dd993a_idx'), models.Index(fields=['ip_address', 'viewed_at'], name='core_postvi_ip_addr_908f2c_idx')],
            },
        ),
    ]
