# Generated by Django 5.2.6 on 2025-09-23 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0016_add_post_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('post_like', 'Liked Post'), ('post_unlike', 'Unliked Post'), ('post_comment', 'Commented on Post'), ('post_bookmark', 'Bookmarked Post'), ('post_unbookmark', 'Unbookmarked Post'), ('post_view', 'Viewed Post'), ('post_share', 'Shared Post'), ('church_follow', 'Followed Church'), ('church_unfollow', 'Unfollowed Church'), ('booking_create', 'Created Booking'), ('booking_update', 'Updated Booking'), ('booking_cancel', 'Cancelled Booking'), ('profile_update', 'Updated Profile'), ('login', 'Logged In'), ('logout', 'Logged Out')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Interaction',
                'verbose_name_plural': 'User Interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_userin_user_id_5676cc_idx'), models.Index(fields=['activity_type', '-created_at'], name='core_userin_activit_64a7eb_idx'), models.Index(fields=['content_type', 'object_id'], name='core_userin_content_65ab15_idx')],
            },
        ),
    ]
