# Generated by Django 5.2.6 on 2025-09-23 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userinteraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='activity_type',
            field=models.CharField(choices=[('post_like', 'Liked Post'), ('post_unlike', 'Unliked Post'), ('post_comment', 'Commented on Post'), ('post_bookmark', 'Bookmarked Post'), ('post_unbookmark', 'Unbookmarked Post'), ('post_view', 'Viewed Post'), ('post_share', 'Shared Post'), ('church_follow', 'Followed Church'), ('church_unfollow', 'Unfollowed Church'), ('booking_create', 'Created Booking'), ('booking_update', 'Updated Booking'), ('booking_cancel', 'Cancelled Booking'), ('service_review', 'Reviewed Service'), ('profile_update', 'Updated Profile'), ('login', 'Logged In'), ('logout', 'Logged Out')], max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Star - Poor'), (2, '2 Stars - Fair'), (3, '3 Stars - Good'), (4, '4 Stars - Very Good'), (5, '5 Stars - Excellent')], help_text='Rating from 1 to 5 stars')),
                ('title', models.CharField(help_text='Review title/summary', max_length=200)),
                ('comment', models.TextField(help_text='Detailed review comment')),
                ('staff_rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 Star - Poor'), (2, '2 Stars - Fair'), (3, '3 Stars - Good'), (4, '4 Stars - Very Good'), (5, '5 Stars - Excellent')], help_text='Staff friendliness', null=True)),
                ('facility_rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 Star - Poor'), (2, '2 Stars - Fair'), (3, '3 Stars - Good'), (4, '4 Stars - Very Good'), (5, '5 Stars - Excellent')], help_text='Facility quality', null=True)),
                ('value_rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 Star - Poor'), (2, '2 Stars - Fair'), (3, '3 Stars - Good'), (4, '4 Stars - Very Good'), (5, '5 Stars - Excellent')], help_text='Value for money', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this review is visible')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide reviewer name')),
                ('helpful_votes', models.PositiveIntegerField(default=0, help_text='Number of helpful votes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='core.booking')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to='core.church')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.bookableservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Review',
                'verbose_name_plural': 'Service Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes_records', to='core.servicereview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_helpful_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Helpful Vote',
                'verbose_name_plural': 'Review Helpful Votes',
            },
        ),
        migrations.AddIndex(
            model_name='servicereview',
            index=models.Index(fields=['service', '-created_at'], name='core_servic_service_a7c263_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereview',
            index=models.Index(fields=['church', '-created_at'], name='core_servic_church__b00343_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereview',
            index=models.Index(fields=['rating', '-created_at'], name='core_servic_rating_2723f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicereview',
            unique_together={('user', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='servicereviewhelpful',
            unique_together={('user', 'review')},
        ),
    ]
