# Generated by Django 5.2.6 on 2025-09-24 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_userinteraction_activity_type_servicereview_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicereview',
            index=models.Index(fields=['booking'], name='core_servic_booking_6a1256_idx'),
        ),
    ]
