# Generated by Django 5.2.6 on 2025-10-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_post_report_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_end_date',
            field=models.DateTimeField(blank=True, help_text='Event end date and time', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='event_location',
            field=models.CharField(blank=True, help_text='Event location/venue', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='event_start_date',
            field=models.DateTimeField(blank=True, help_text='Event start date and time', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='event_title',
            field=models.CharField(blank=True, help_text='Title of the event', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of participants (optional)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('general', 'General Post'), ('photo', 'Photo Post'), ('event', 'Event Post'), ('prayer', 'Prayer Request')], default='general', max_length=20),
        ),
    ]
