# Generated by Django 5.2.6 on 2025-10-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_post_event_end_date_post_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='donation_description',
            field=models.TextField(blank=True, help_text='Description of what the donation is for'),
        ),
        migrations.AddField(
            model_name='post',
            name='donation_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional donation goal amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='enable_donation',
            field=models.BooleanField(default=False, help_text='Enable donations for this post'),
        ),
        migrations.AlterField(
            model_name='church',
            name='denomination',
            field=models.CharField(choices=[('catholic', 'Roman Catholic Church'), ('iglesia_ni_cristo', 'Iglesia ni Cristo (INC)'), ('protestant', 'Protestant (Other)'), ('uccp', 'United Church of Christ in the Philippines (UCCP)'), ('baptist', 'Baptist'), ('methodist', 'Methodist'), ('presbyterian', 'Presbyterian'), ('lutheran', 'Lutheran'), ('adventist', 'Seventh-day Adventist'), ('pentecostal', 'Pentecostal'), ('evangelical', 'Evangelical'), ('mormon', 'The Church of Jesus Christ of Latter-day Saints (Mormons)'), ('jehovah', "Jehovah's Witnesses"), ('orthodox', 'Orthodox'), ('islam', 'Islam'), ('buddhism', 'Buddhism'), ('hinduism', 'Hinduism'), ('indigenous', 'Indigenous Beliefs'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
