# Generated by Django 5.2.6 on 2025-10-06 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_donation_to_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='donation_description',
        ),
    ]
