# Generated by Django 5.2.6 on 2025-10-06 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_donation_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Donation amount', max_digits=10)),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('message', models.TextField(blank=True, help_text='Optional message from donor')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide donor name from public')),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('gcash', 'GCash'), ('paymongo', 'PayMongo'), ('bank', 'Bank Transfer')], default='paypal', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paypal_order_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('paypal_payer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('paypal_transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_made', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.post')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_donati_created_ed4d90_idx'), models.Index(fields=['post', 'payment_status'], name='core_donati_post_id_740bfa_idx')],
            },
        ),
    ]
