# Generated by Django 5.2.6 on 2025-10-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='paypal_email',
            field=models.EmailField(blank=True, help_text='PayPal email address for receiving donations (required to enable donations on posts)', max_length=254, null=True),
        ),
    ]
