# Generated by Django 5.2.6 on 2025-10-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_add_church_paypal_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="barangay",
            field=models.CharField(blank=True, help_text="Barangay", max_length=200),
        ),
        migrations.AddField(
            model_name="church",
            name="city_municipality",
            field=models.CharField(
                blank=True, help_text="City or Municipality", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="province",
            field=models.CharField(blank=True, help_text="Province", max_length=200),
        ),
        migrations.AddField(
            model_name="church",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="Region (e.g., Region X - Northern Mindanao)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="street_address",
            field=models.CharField(
                blank=True, help_text="Street, Building, Unit No.", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="church",
            name="address",
            field=models.TextField(blank=True, help_text="Street address (legacy)"),
        ),
        migrations.AlterField(
            model_name="church",
            name="city",
            field=models.CharField(
                blank=True, help_text="City (legacy)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="church",
            name="postal_code",
            field=models.CharField(
                blank=True, help_text="4-digit Postal/ZIP code", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="church",
            name="state",
            field=models.CharField(
                blank=True, help_text="State/Province (legacy)", max_length=100
            ),
        ),
    ]
