# Generated by Django 4.2.7 on 2025-10-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_add_message_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="stripe_charge_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="stripe_payment_method_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="donation",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("paypal", "PayPal"),
                    ("stripe", "Credit Card"),
                    ("gcash", "GCash"),
                    ("paymongo", "PayMongo"),
                    ("bank", "Bank Transfer"),
                ],
                default="paypal",
                max_length=20,
            ),
        ),
    ]
