# Generated by Django 4.2.7 on 2025-10-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_add_stripe_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking_requested", "New Booking Request"),
                    ("booking_reviewed", "Booking Reviewed"),
                    ("booking_approved", "Booking Approved"),
                    ("booking_declined", "Booking Declined"),
                    ("booking_canceled", "Booking Canceled"),
                    ("booking_completed", "Booking Completed"),
                    ("church_approved", "Church Approved"),
                    ("church_declined", "Church Declined"),
                    ("church_assignment", "Church Manager Assignment"),
                    ("follow_request", "Follow Request"),
                    ("follow_accepted", "Follow Accepted"),
                    ("message_received", "New Message"),
                ],
                max_length=50,
            ),
        ),
    ]
