# Generated by Django 4.2.7 on 2025-10-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_add_church_assignment_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="church",
            name="slug",
            field=models.SlugField(
                help_text="URL-friendly version of the name",
                max_length=200,
                unique=True,
            ),
        ),
    ]
