# Generated by Django 4.2.7 on 2025-10-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_increase_church_slug_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="church",
            name="denomination",
            field=models.CharField(
                choices=[
                    ("catholic", "Roman Catholic Church"),
                    ("parish", "Roman Catholic Parish"),
                    ("chapel", "Roman Catholic Chapel"),
                    ("shrine", "Roman Catholic Shrine"),
                    ("cathedral", "Roman Catholic Cathedral"),
                    ("basilica", "Roman Catholic Basilica"),
                    ("other", "Other Catholic Community"),
                ],
                default="parish",
                max_length=20,
            ),
        ),
    ]
