# Generated by Django 4.2.7 on 2025-10-20 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0034_update_denomination_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="church",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created/manages this church (can be null for managerless churches)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_churches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
