# Generated by Django 4.2.7 on 2025-10-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_make_church_owner_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Payment amount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when payment was completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paypal", "PayPal"),
                    ("stripe", "Credit Card"),
                    ("gcash", "GCash"),
                ],
                help_text="Payment method used",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                help_text="Payment status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Payment gateway transaction ID",
                max_length=200,
                null=True,
            ),
        ),
    ]
