# Generated by Django 4.2.7 on 2025-10-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_booking_payment_amount_booking_payment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                help_text="Payment status",
                max_length=20,
            ),
        ),
    ]
