# Generated by Django 4.2.7 on 2025-11-01 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0041_churchstaff"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="handled_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Parish administrator who handled this booking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
