# Generated by Django 4.2.7 on 2025-11-02 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_booking_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("approve", "Approved"),
                            ("reject", "Rejected"),
                            ("cancel", "Canceled"),
                            ("view", "Viewed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("service", "Service"),
                            ("booking", "Booking"),
                            ("post", "Post"),
                            ("availability", "Availability"),
                            ("staff", "Staff Management"),
                            ("event", "Event"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the action performed"),
                ),
                (
                    "target_id",
                    models.IntegerField(
                        blank=True, help_text="ID of the affected object", null=True
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of the affected object",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_activities",
                        to="core.church",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="core.churchstaff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Activity Log",
                "verbose_name_plural": "Staff Activity Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["staff", "-created_at"],
                        name="core_staffa_staff_i_76d8ee_idx",
                    ),
                    models.Index(
                        fields=["church", "-created_at"],
                        name="core_staffa_church__f66a25_idx",
                    ),
                ],
            },
        ),
    ]
