# Generated by Django 4.2.7 on 2025-11-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_postimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when message was seen", null=True
            ),
        ),
    ]
