# Generated by Django 5.2.6 on 2025-09-23 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='device_info',
            field=models.CharField(blank=True, help_text='Device information', max_length=200),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address when code was generated', null=True),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent string', max_length=500),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email associated with the activity', max_length=254)),
                ('activity_type', models.CharField(choices=[('registration_started', 'Registration Started'), ('email_verification_sent', 'Email Verification Sent'), ('email_verification_completed', 'Email Verification Completed'), ('registration_completed', 'Registration Completed'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('password_reset_request', 'Password Reset Request'), ('password_reset_completed', 'Password Reset Completed'), ('profile_updated', 'Profile Updated')], max_length=30)),
                ('success', models.BooleanField(default=True, help_text='Whether the activity was successful')),
                ('details', models.TextField(blank=True, help_text='Additional activity details or error messages')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the request')),
                ('user_agent', models.TextField(help_text='User agent string', max_length=500)),
                ('device_info', models.CharField(blank=True, help_text='Parsed device information', max_length=200)),
                ('browser_info', models.CharField(blank=True, help_text='Browser information', max_length=200)),
                ('os_info', models.CharField(blank=True, help_text='Operating system information', max_length=200)),
                ('country', models.CharField(blank=True, help_text='Country based on IP', max_length=100)),
                ('city', models.CharField(blank=True, help_text='City based on IP', max_length=100)),
                ('verification_code', models.CharField(blank=True, help_text='Associated verification code if any', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_us_user_id_439e53_idx'), models.Index(fields=['email', 'created_at'], name='accounts_us_email_419198_idx'), models.Index(fields=['ip_address', 'created_at'], name='accounts_us_ip_addr_f490fa_idx'), models.Index(fields=['activity_type', 'created_at'], name='accounts_us_activit_8b68dc_idx')],
            },
        ),
    ]
