# Generated by Django 5.2.6 on 2025-09-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_user_activity_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when code was generated', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', max_length=500)),
                ('device_info', models.CharField(blank=True, help_text='Device information', max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
