# Generated by Django 5.2.6 on 2025-09-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when code was generated', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', max_length=500)),
                ('device_info', models.CharField(blank=True, help_text='Device information', max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('registration_started', 'Registration Started'), ('email_verification_sent', 'Email Verification Sent'), ('email_verification_completed', 'Email Verification Completed'), ('registration_completed', 'Registration Completed'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('password_reset_request', 'Password Reset Request'), ('password_reset_completed', 'Password Reset Completed'), ('login_code_request', 'Login Code Request'), ('login_code_success', 'Login Code Success'), ('login_code_failed', 'Login Code Failed'), ('profile_updated', 'Profile Updated')], max_length=30),
        ),
    ]
