# Generated by Django 5.2.6 on 2025-10-10 08:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_logincode_alter_useractivity_activity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=accounts.models.get_profile_storage,
                upload_to="profiles/",
            ),
        ),
    ]
