# Generated by Django 5.2.6 on 2025-10-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="barangay",
            field=models.CharField(blank=True, help_text="Barangay", max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="city_municipality",
            field=models.CharField(
                blank=True, help_text="City or Municipality", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="postal_code",
            field=models.CharField(
                blank=True, help_text="Postal/ZIP Code", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="province",
            field=models.CharField(blank=True, help_text="Province", max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="Region (e.g., Region X - Northern Mindanao)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="street_address",
            field=models.CharField(
                blank=True, help_text="Street, Building, Unit No.", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True, help_text="Full address (legacy field)"),
        ),
    ]
