# Generated by Django 4.2.7 on 2025-10-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_profile_barangay_profile_city_municipality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="show_donation_rank",
            field=models.BooleanField(
                default=True, help_text="Show donation rank badge publicly"
            ),
        ),
    ]
